feat: add default color
F0x1d/LogFox pull request #33
Opened 2023-10-01 19:57 UTC by Jesse205

#32

2023-10-01 21:58 UTC, F0x1d requested changes

2023-10-01 21:58 UTC, F0x1d commented on app/src/main/res/values-night/themes.xml
> +        <item name="colorPrimaryInverse">@color/md_theme_dark_inversePrimary</item>
Please, move these colors tags above all the others of the theme

2023-10-01 21:58 UTC, F0x1d commented on app/src/main/res/values/themes.xml
> +        <item name="colorPrimaryInverse">@color/md_theme_light_inversePrimary</item>
Same here

2023-10-01 21:58 UTC, F0x1d commented on app/src/main/res/values/colors.xml
> +    <color name="md_theme_dark_scrim">#000000</color>
Maybe also separate colors to values and values-night?

2023-10-02 06:50 UTC, Jesse205 commented
I also moved the card shadow and removed the night version of themes.xml because the two theme.xml have a lot of duplicate code.

2023-10-02 07:10 UTC, F0x1d approved these changes

2023-10-02 07:16 UTC, F0x1d commented
<img width="255" alt="image" src="https://github.com/F0x1d/LogFox/assets/39910552/cb13f6ef-2b55-40f0-be95-c8dfe53f1055">

Found a small bug

2023-10-02 07:55 UTC, F0x1d commented
Looks like `android:textColorHighlight` should be defined separately, that's strange

2023-10-02 07:57 UTC, Jesse205 commented
![image](https://github.com/F0x1d/LogFox/assets/51242302/a7ccc106-766d-4410-92db-bf8af51a6f54)
![image](https://github.com/F0x1d/LogFox/assets/51242302/0d2785cf-e3ac-4e53-8ae4-3666156a8c5c)

Material Components doesn't map color values to attr, I need to either switch to token or copy these files and modify them one by one. The current app doesn't use multiple themes, so I'll be using tokens to set the default colors.

The downside of using tokens is that on Android 12+ devices that don't support dynamic color picking, the software will still use the system-supplied colors instead of the app's branded colors!

2023-10-02 08:09 UTC, F0x1d commented
Maybe copy this few files and replace with theme attribute?

2023-10-02 09:04 UTC, merged