Feat md color
F0x1d/LogFox pull request #51
Opened 2023-10-11 19:15 UTC by Jesse205

![Screenshot_2023-10-12-03-10-59-299_com f0x1d logfox](https://github.com/F0x1d/LogFox/assets/51242302/05835095-a198-457a-8b71-11a0c4346d2d)
![Screenshot_2023-10-12-03-11-16-816_com f0x1d logfox](https://github.com/F0x1d/LogFox/assets/51242302/6c66d8c1-7ece-4dad-9670-56d6f07d0779)
https://github.com/F0x1d/LogFox/issues/50

2023-10-12 00:00 UTC, F0x1d commented on app/src/main/java/com/f0x1d/logfox/extensions/logline/LogLevelExtensions.kt
> +})
Same

2023-10-12 09:26 UTC, F0x1d requested changes
I really can't think of best way to store and fill this map right now, maybe you have something better in mind?

2023-10-12 09:26 UTC, F0x1d commented on app/src/main/java/com/f0x1d/logfox/ui/fragment/LogsFragment.kt
> +    private val levelColorCacheMap = mutableMapOf<Int, Int>()
I don't really like this to be here. Maybe it will be better to store and fill them ?lazily? in `Adapter`, or in constructor

2023-10-12 09:26 UTC, F0x1d commented on app/src/main/java/com/f0x1d/logfox/extensions/logline/LogLevelExtensions.kt
> +    return foregroundColorIdByLevel().let { colorId ->
check method `getOrPut`, I guess it can simplify this block of code

2023-10-12 09:26 UTC, F0x1d commented on app/src/main/java/com/f0x1d/logfox/extensions/logline/LogLevelExtensions.kt
> +    return backgroundColorIdByLevel().let { colorId ->
Same about `getOrPut`

2023-10-12 09:26 UTC, F0x1d commented on app/src/main/java/com/f0x1d/logfox/ui/viewholder/LogViewHolder.kt
> +    private val levelColorCacheMap: MutableMap<Int, Int>,
I don't think viewHolder should receive `MutableMap`, at least just `Map`. Anyway maybe it's better to access it from adapter via `adapter()` method?

2023-10-12 22:18 UTC, F0x1d commented on app/src/main/java/com/f0x1d/logfox/extensions/logline/LogLevelExtensions.kt
> +fun LogLevel.backgroundColorByLevel(context: Context, levelColorCacheMap: MutableMap<Int, Int>): Int {
Please, replace with something like 
```
= backgroundColorIdByLevel().let { 
    levelColorCacheMap.getOrPut(it) { 
        context.getColor(it) 
    }
}
```

2023-10-12 22:18 UTC, F0x1d commented on app/src/main/java/com/f0x1d/logfox/extensions/logline/LogLevelExtensions.kt
> +    return foregroundColorIdByLevel().let { levelColorCacheMap.getOrPut(it) { context.getColor(it) }}
Same here

2023-10-12 23:16 UTC, Jesse205 commented
If use di, my idea is to set the lifecycle of the map to the lifecycle of the activity, because the color values in dark mode are different from those in bright mode.

Due to wrapping a `ContextWapper` is the context of View, I need to obtain the `baseContext`. But I cannot guarantee that `baseContext` can obtain `Activity` every time, and I cannot guarantee that the view `context` is always an `ContextWapper` in the future.

`Another method is to pass an `Activity` to the adapter.`

2023-10-13 07:49 UTC, F0x1d commented
I've wanted something like this, but I still don't know if it looks ok

2023-10-13 20:58 UTC, F0x1d commented
What do you think about it now? BTW, aren't the colors in night mode a kind of dark, I don't really like them

2023-10-13 21:01 UTC, F0x1d requested changes

2023-10-13 21:01 UTC, F0x1d commented on app/src/main/res/values-night/colors_material3.xml
> +    <color name="yellow_on_container">#f9e534</color>
Something about them is not ok... Maybe I'm a bit of colorblind? You tell me

2023-10-13 21:20 UTC, Jesse205 commented
I don't know either. I am currently learning more about Android through this and more project.😂I think the current plan is quite good.

The color of the night mode is generated by me from the generator, and the container color is like this. I think this color is just right, very beautiful, and also very comfortable. I don't think the color of night mode is too bright.

If you don't like it, I can change it to primary and on_primary The color has the same brightness as the error color

2023-10-13 21:27 UTC, Jesse205 commented
But the contrast is indeed a bit low

2023-10-13 21:48 UTC, Jesse205 commented
![Screenshot_2023-10-14-05-35-31-542_com.f0x1d.logfox.jpg](https://github.com/F0x1d/LogFox/assets/51242302/2a3ed8d1-35c1-4979-9fdd-b4aa16d5c85c)
![Screenshot_2023-10-14-05-35-13-289_com.f0x1d.logfox.jpg](https://github.com/F0x1d/LogFox/assets/51242302/45f0292f-5d65-4747-b0da-529673e74f11)

This is the performance of using all primary colors in both light and dark modes.

2023-10-13 21:52 UTC, Jesse205 commented
Do you want to use container colors in bright mode and primary colors in dark mode? This will ensure that the level background does not darken. And all the colors look great.

2023-10-13 21:53 UTC, F0x1d commented
Let's give it a try

2023-10-13 22:16 UTC, F0x1d commented
Yeah, they are nice now

2023-10-13 22:16 UTC, F0x1d approved these changes

2023-10-13 22:17 UTC, F0x1d commented
Is this all, can PR be merged?

2023-10-13 22:19 UTC, Jesse205 commented
Yes. The label colors have been separated from those defined colors, and you can modify these colors at any time. I don't have any other ideas at the moment. If there are any, I will open a new PR.

2023-10-13 22:21 UTC, merged